### ISSUE TITLE
docs: more docs!

### ISSUE THREAD

**Issue by ByFox213** [teeworlds-nats/bridge#83]
```
nats:
  from:
    - "tw.{{type}}.write.{{server_name}}"
    - "tw.t2.sync"
  to:
    - "tw.{{type}}.read.{{server_name}}"
  server:
    - "nats://nats.nats:4222"
  queue: "" # Required value to be sent to all "econ" services, not just one of the queues.

econ:
  host: "{{server_name}}.{{type}}-tw:8000"
  password: tf
  first_commands:
    - "say [SYSTEM] ECON Bridge connected!"
  tasks:
    - command: "bans_save bans/b"
      delay: 30
    - command: ""# attempt to send a message to the server to re-establish the connection if it fails to send it
      delay: 5

args:
  server_name: "fng-1"
  type: "fng"
```
And add all values or schema to a separate file, you can also use github wiki
