### ISSUE TITLE
econ: Messages from tasks are sent in the wrong order

### ISSUE THREAD

**Issue by ByFox213** [teeworlds-nats/bridge#84]
```
econ:
  tasks:
    - command: "foo"
      delay: 1
    - command: "bar"
      delay: 1
```

It's just a matter of turning the list over

We should remember to do it in handler::paths too
