### ISSUE TITLE
econ: upgrade tasks

### ISSUE THREAD

**Issue by ByFox213** [teeworlds-nats/bridge#86]
```
econ:
  tasks:
    - cron: "*" # or
      commands: 
        - "foo"
      type: random # ["line", "random", "all"], default: line
    - delay: 5 # or
      commands: "bar"
```
We need to define in commands whether it is a list or not, preferably without #.
